stages:
  - static-analysis
  - build

static-analysis:
  stage: static-analysis
  tags:
    - docker
  image: $CI_REGISTRY/microservice/core-bluprint/poetry.dev:latest
  variables:
    GIT_STRATEGY: clone
  script:
    - poetry run -q ruff check --ignore-noqa .
    - poetry run -q codespell --check-filenames
    - poetry run -q black --check --preview .
    - poetry run -q isort --check .
    - poetry check
    - poetry run -q mypy .
    - find . -name '*.py' -exec poetry run -q pyupgrade --py312-plus {} \;
    - git diff --quiet
  after_script:
    - >
      if [ $CI_JOB_STATUS == 'failed' ]; then
        echo $(git --no-pager diff)
      fi

build-core:
  stage: build
  tags:
    - docker
  image: $CI_REGISTRY/microservice/core-bluprint/system:latest
  script:
    - poetry build
    - poetry config repositories.nexus-registry "https://nexus.bluprint.ir/repository/private-package-registry/"
    - poetry config http-basic.nexus-registry $NEXUS_USERNAME $NEXUS_PASSWORD
    - poetry publish --repository nexus-registry
  only:
    - main
