stages:
  - static-analysis
  - build

static-analysis:
  stage: static-analysis
  tags:
    - docker
  image: $CI_REGISTRY/microservice/core-zenoa/poetry.dev:latest
  variables:
    GIT_STRATEGY: clone
  script:
    - poetry run -q ruff check --ignore-noqa .
    - poetry run -q codespell --check-filenames
    - poetry run -q black --check --preview .
    - poetry run -q isort --check .
    - poetry check
    - poetry run -q mypy .
    - find . -name '*.py' -exec poetry run -q pyupgrade --py312-plus {} \;
    - git diff --quiet
  after_script:
    - >
      if [ $CI_JOB_STATUS == 'failed' ]; then
        echo $(git --no-pager diff)
      fi

build-core:
  stage: build
  tags:
    - docker
  image: $CI_REGISTRY/microservice/core-zenoa/system:latest
  script:
    - poetry config repositories.gitlab "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi"
    - poetry config http-basic.gitlab gitlab-ci-token "$CI_JOB_TOKEN"
    - poetry publish --build --repository gitlab
  only:
    - main
