[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79

[tool.codespell]
ignore-words-list = "nin,astroid"

[tool.mypy]
plugins = ["pydantic.mypy"]
ignore_missing_imports = true


follow_imports = 'normal'
[[tool.mypy.overrides]]
module = 'redis.asyncio.client'
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = 'redis.asyncio'
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = 'redis'
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = 'dateutil.relativedelta'
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = 'requests'
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = 'aiofiles'
ignore_missing_imports = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true

[tool.poetry]
name = "core-zenoa"
version = "0.2.0"
description = "Core package"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
jdatetime = "^4.1.1"
beanie = "1.26.0"
python-jose = "^3.3.0"
pydantic = { version = "^2.10.3", extras = ["email"] }
pydantic-settings = "^2.1.0"
uvicorn = "^0.30.0"
orjson = "3.10.14"
pyyaml = "^6.0.2"

# fastapi = { version = "^0.111", optional = true }
fastapi = { version = "^0.115", optional = true }
python-multipart = { version = "*", optional = true }
faststream = { version = "^0.5.28", extras = ["rabbit", "otel"], optional = true }
celery = { version = "^5.3.6", optional = true }
httpx = { version = "^0.26.0", optional = true }
requests = { version = "^2.31.0", optional = true }
redis = { version = "^5.0.1", optional = true }
openai = {version = "^1.51.2", optional = true}

# OTEL
logfire = "^1.1.0"
sentry-sdk = { extras = ["fastapi"], version = "^1.39.1" }
opentelemetry-distro = "0.48b0"
opentelemetry-exporter-otlp = "^1.22.0"
opentelemetry-instrumentation-logging = { version = "*" }
opentelemetry-instrumentation-urllib = { version = "*" }
opentelemetry-instrumentation-system-metrics = { version = "*" }
opentelemetry-instrumentation-urllib3 = { version = "*" }
opentelemetry-instrumentation-asgi = { version = "*", optional = true }
opentelemetry-instrumentation-fastapi = ">0.46b"
opentelemetry-instrumentation-aio-pika = { version = "*", optional = true }
opentelemetry-instrumentation-celery = { version = "*", optional = true }
opentelemetry-instrumentation-httpx = { version = "*", optional = true }
opentelemetry-instrumentation-requests = { version = "*", optional = true }
opentelemetry-instrumentation-redis = { version = "*", optional = true }
opentelemetry-instrumentation-pymongo = { version = "*", optional = true }

[tool.poetry.extras]
FastAPI = [
    "fastapi",
    "python-multipart",
    "uvicorn",
    "opentelemetry-instrumentation-asgi",
    "opentelemetry-instrumentation-fastapi",
]
Rabbit = [
    "fastapi",
    "uvicorn",
    "faststream",
    "opentelemetry-instrumentation-asgi",
    "opentelemetry-instrumentation-fastapi",
    "opentelemetry-instrumentation-aio-pika",
]
Celery = ["celery", "opentelemetry-instrumentation-celery"]
HTTPx = ["httpx", "opentelemetry-instrumentation-httpx"]
Requests = ["requests", "opentelemetry-instrumentation-requests"]
Redis = ["redis", "opentelemetry-instrumentation-redis"]
Mongodb = ["beanie", "opentelemetry-instrumentation-pymongo"]
OpenAI = ["openai"]

[tool.poetry.group.test.dependencies]
pytest-asyncio = "^0.21.1"
deepdiff = "^6.7.0"
pytest = "^7.4.3"
pytest-mock = "^3.12.0"
freezegun = "^1.2.2"
pytest-cov = "^4.1.0"
pytest-xdist = "^3.5.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
mypy = "^1.5.1"
pydantic = "^2.7.1"
flake8 = "^6.1.0"
black = "^24.2.0"
isort = "^5.12.0"
ipykernel = "^6.25.1"
ipywidgets = "^8.1.1"
pre-commit = "^3.6.0"
ruff = "^0.4.4"
codespell = "^2.2.6"
pyupgrade = "^3.15.2"
types-pyyaml = "^6.0.12.20240917"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
