name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-env

      - name: Run pre-commit
        run: |
          poetry run pre-commit run --all-files --show-diff-on-failure
          git diff --quiet || (echo "Code formatting failed"; git --no-pager diff; exit 1)

  publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    needs: static-analysis
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-env

      - name: Build
        run: poetry build
        shell: bash

      - name: Publish to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish
